project:
  type: book

book:
  title: ENaC isn't ASIC
  subtitle: "A Study of Various Activating Mutations and Conditions of the Epithelial Sodium Channel"
  author:
    - name: "Richard Posert"
      affiliation: Baconguis Lab, Vollum Institute, OHSU
  date: "7/21/2023"
  chapters:
    - index.qmd
    - part: parts/introduction.qmd
      chapters:
       - parts/introduction/intro_enac-in-the-body.qmd
       - parts/introduction/intro_enac-as-a-channel.qmd
    - part: parts/results.qmd
      chapters:
        - parts/results/results_transmembrane-domain.qmd
        - parts/results/results_activating-conditions.qmd
    - parts/references.qmd
  appendices: 
    - parts/appendices/mat-meth.qmd
    - parts/appendices/processing-flow.qmd
    - parts/appendices/validation.qmd
    - parts/appendices/code.qmd
  navbar: 
    logo: figures/other/domain-cartoon_ECD.png
  search:
    location: navbar
    type: overlay
  downloads:
    - pdf
    - docx
  output-file: posert-dissertation

csl: cell.csl
toc: true
bibliography: henac.bib
format-links: true

format:
  html: 
    filters:
      - lightbox
    lightbox:
      match: auto
    mainfont: Charter
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrbook
    pdf-engine: latexmk
    pdf-engine-opt: --xelatex
    latex-max-runs: 3
    keep-tex: false
    link-citations: true
    colorlinks: false
    geometry:
      - left=2in
      - right=2in
      - marginparwidth=1.5in
      - twoside=true
    include-in-header:
      - text: |
          \usepackage{fontspec}
          \usepackage{newunicodechar}
          \newfontfamily\expandedfont{Fira Sans}
          \newfontfamily\symbolfont{STIX Two Math}
          \setmainfont{Charter}
          \setsansfont{Montserrat}
          \setmonofont{JetBrains Mono NL}

          \DeclareTextFontCommand{\textfallback}{\expandedfont}
          \DeclareTextFontCommand{\symbolfallback}{\symbolfont}
          \newunicodechar{→}{\textfallback{→}}
          \newunicodechar{₂}{\textfallback{₂}}
          \newunicodechar{⁻}{\textfallback{⁻}}
          \newunicodechar{ă}{\textfallback{ă}}
          \newunicodechar{≠}{\textfallback{≠}}
          \newunicodechar{≅}{\symbolfont{≅}}
          % naughty naughty but who cares, just don't use a non-breaking hyphen
          \newunicodechar{‑}{\textfallback{-}}
          \newunicodechar{ }{ }

          \usepackage{ucharclasses}
          \setTransitionsForGreek{\begingroup\symbolfont}{\endgroup}

          \usepackage{lscape}
          \newcommand{\blandscape}{\begin{landscape}}
          \newcommand{\elandscape}{\end{landscape}}
  docx:
    reference-doc: dissertation-reference.docx
    filters:
      - no_asides.lua
