project:
  type: book

book:
  title: ENaC isn't ASIC
  subtitle: "A Study of Various Activating Mutations and Conditions of the Epithelial Sodium Channel"
  author:
    - name: "Richard Posert"
      affiliation: Baconguis Lab, Vollum Institute, OHSU
  date: "7/21/2023"
  chapters:
    - index.qmd
    - part: parts/introduction.qmd
      chapters:
       - parts/introduction/intro_enac-in-the-body.qmd
    - parts/references.qmd
  navbar: 
    logo: figures/other/domain-cartoon_ECD.png
  search:
    location: navbar
    type: overlay
  downloads:
    - pdf
    - docx
  output-file: posert-dissertation

csl: nature.csl
toc: true
bibliography: henac.bib
format-links: true

format:
  html: 
    mainfont: Charter
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrbook
    colorlinks: false
    geometry:
      - left=2in
      - right=2in
      - marginparwidth=1.5in
      - twoside=true
    include-in-header:
      - text: |
          \usepackage{fontspec}
          \newfontfamily\defaultfont{Charter}
          \newfontfamily\greekfont{Fira Sans}

          \usepackage{ucharclasses}
          \setTransitionsForLatin{\defaultfont}{}
          \setTransitionsForGreek{\greekfont}{\defaultfont}
  docx:
    reference-doc: dissertation-reference.docx
